version: "3.9"
services: 
  web:
    build: ./wallet
    ports:
      - "8000:8000"
    command: >
      bash -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      echo \"from django.contrib.auth import get_user_model; User=get_user_model(); User.objects.create_superuser('admin', 'admin@example.com', 'admin') if not User.objects.filter(username='admin') else ''\" | python manage.py shell &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - db:/code/db

volumes:
  db:


